### PR TITLE
Add support for events API

### PR DESCRIPTION
**Pull request by fernandes**
This is the documentation for event API

http://docs.vmd.citrix.com/XenServer/6.2.0/1.0/en_gb/api/?c=event

__Usage__

```ruby
conn.event.register(["*"])
conn.event.next # next blocks waiting for next event
```

actually is returning a hash with event details, example, if someone trigger a `SR.scan`, the event is

```ruby
=> {"id"=>"433",
 "timestamp"=>"1463421721.",
 "class"=>"task",
 "operation"=>"add",
 "ref"=>"OpaqueRef:0255a381-414b-a583-ff20-3d58a96e219b",
 "snapshot"=>
  {"uuid"=>"386bd667-2713-9d09-6ce0-4c5602254b67",
   "name_label"=>"SR.scan",
   "name_description"=>"",
   "allowed_operations"=>[],
   "current_operations"=>{},
   "created"=>#<XMLRPC::DateTime:0x007fd91f3086a8 @day=16, @hour=18, @min=2, @month=5, @sec=1, @year=2016>,
   "finished"=>#<XMLRPC::DateTime:0x007fd9176376d8 @day=1, @hour=0, @min=0, @month=1, @sec=0, @year=1970>,
   "status"=>"pending",
   "resident_on"=>"OpaqueRef:7f39cd64-a08b-042a-1bed-244e519bd2f3",
   "progress"=>0.0,
   "type"=>"<none/>",
   "result"=>"",
   "error_info"=>[],
   "other_config"=>{},
   "subtask_of"=>"OpaqueRef:NULL",
   "subtasks"=>[]}}
```

### CODE REVIEW

**Comment by plribeiro3000** [comment]
@fernandes Can you fix the stylish comments by @houndci-bot ?

Also, would be nice to have some tests at least for the new model `Event`.

**Comment by fernandes** [comment]
@plribeiro3000 done!

**Comment by plribeiro3000** [comment]
👍

**Comment by plribeiro3000** [comment]
@fernandes The build is broken. do you think it is related to this changes?

**Comment by fernandes** [comment]
no, the eight errors are related to net/http, seems it's trying to connect to a running XenServer instance

seems it's not loading the VCR Cassetes, weird hahaha

[Cassette: 'create_server_get_all_hosts'] Initialized HTTPInteractionList with request matchers [:method, :uri] and 1 interaction(s): { [post http://192.168.10.2/] => [200 "<methodResponse><params><param><value><struct><member><name>Status</name><value>"] }

**Comment by plribeiro3000** [comment]
It also seems we are having issues with rubygems since is failing to install some gems in the first try. =s

**Comment by fernandes** [comment]
yeah, it's weird...

build for master https://travis-ci.org/fog/fog-xenserver/branches is also erroring too

**Comment by plribeiro3000** [comment]
Yeah. I guess i will create a ticket to look at it later.

**Comment by plribeiro3000** [comment]
Thanks for your contribution!

**Comment by fernandes** [comment]
😎 👍

**Pull request merged**
